config/routes.rb
# == Route Map
#
#       Prefix Verb   URI Pattern                  Controller#Action
#  session_new GET    /session/new(.:format)       session#new
#         root GET    /                            pages#home
#   edit_users GET    /users/edit(.:format)        users#edit
#        users GET    /users(.:format)             users#index
#              POST   /users(.:format)             users#create
#     new_user GET    /users/new(.:format)         users#new
#         user PATCH  /users/:id(.:format)         users#update
#              PUT    /users/:id(.:format)         users#update
#              DELETE /users/:id(.:format)         users#destroy
#     monsters GET    /monsters(.:format)          monsters#index
#              POST   /monsters(.:format)          monsters#create
#  new_monster GET    /monsters/new(.:format)      monsters#new
# edit_monster GET    /monsters/:id/edit(.:format) monsters#edit
#      monster GET    /monsters/:id(.:format)      monsters#show
#              PATCH  /monsters/:id(.:format)      monsters#update
#              PUT    /monsters/:id(.:format)      monsters#update
#              DELETE /monsters/:id(.:format)      monsters#destroy
#       spells GET    /spells(.:format)            spells#index
#              POST   /spells(.:format)            spells#create
#    new_spell GET    /spells/new(.:format)        spells#new
#   edit_spell GET    /spells/:id/edit(.:format)   spells#edit
#        spell GET    /spells/:id(.:format)        spells#show
#              PATCH  /spells/:id(.:format)        spells#update
#              PUT    /spells/:id(.:format)        spells#update
#              DELETE /spells/:id(.:format)        spells#destroy
#        zones GET    /zones(.:format)             zones#index
#              POST   /zones(.:format)             zones#create
#     new_zone GET    /zones/new(.:format)         zones#new
#    edit_zone GET    /zones/:id/edit(.:format)    zones#edit
#         zone GET    /zones/:id(.:format)         zones#show
#              PATCH  /zones/:id(.:format)         zones#update
#              PUT    /zones/:id(.:format)         zones#update
#              DELETE /zones/:id(.:format)         zones#destroy
#        login GET    /login(.:format)             session#new
#              POST   /login(.:format)             session#create
#              DELETE /login(.:format)             session#destroy
#

Rails.application.routes.draw do

 get 'attack/:id' => 'monsters#attack', :as => 'monster_attack'

 get 'damage' => 'monsters#damage', :as => 'monster_damage'

 post 'combat' => 'monsters#combat', :as => 'monster_combat'

 get 'result' => 'monsters#result', :as => 'monster_result'



 get 'session/new'

 root :to => 'pages#home'

 get 'search' => 'pages#search'

 post 'search' => 'pages#anymon'



   resources :users, :except => [:edit] do   #rerouting for edit profile
    collection do
      get '/edit' => 'users#edit'
    end
  end

  resources :monsters, :spells, :zones

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'


end

app/models/monster.rb
# == Schema Information
#
# Table name: monsters
#
#  id          :integer          not null, primary key
#  name        :string
#  image       :text
#  deaths      :integer
#  lng         :float
#  lat         :float
#  suburb      :string
#  country     :string
#  state       :string
#  xp          :integer
#  gold        :integer
#  level       :integer
#  health      :integer
#  rank        :string
#  attack      :integer
#  damage      :integer
#  speed       :integer
#  defence     :integer
#  affinity    :string
#  user_id     :integer
#  alive       :boolean          default(TRUE)
#  tagged      :boolean          default(FALSE)
#  attacker_id :integer
#  created_at  :datetime
#  updated_at  :datetime
#  zone_id     :integer
#

class Monster < ActiveRecord::Base
  belongs_to :user
  belongs_to :zone
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  include MonstersHelper
  include UsersHelper

  def index
      @monsters = Monster.all
  end

  def attack
    # if alive? go back to search
    @monster = Monster.find params[:id]
    
  end



  def damage


    if params[:monster_id]
      @monster = Monster.find params[:monster_id]
         @monster.attacker_id = @current_user.id
        @monster.tagged = true
        @monster.save
    
    else
     @monster = Monster.find_by :attacker_id => @current_user.id
    end

      if @monster.attacker_id == @current_user.id || @monster.tagged == false

          if @current_user.health <= 0 || @monster.alive == false
            
            redirect_to monster_result_path
          end

          @monster.attacker_id = @current_user.id
          @monster.tagged = true
          @monster.save
          gon.monster_id = @monster.id
          gon.m_health = @monster.health
          gon.m_max_health = @monster.max_health
          gon.m_injury = @monster.injury
          gon.p_health = @current_user.health
          gon.p_max_health = @current_user.max_health
          gon.p_injury = @current_user.injury
          gon.p_move = @current_user.move_first
          gon.winner = @current_user.winner
          gon.battle = @current_user.in_battle

          @player_spells = how_manyspells

      end
  end


  def combat

    atk =0
    dmg =0
    defence =0
    spd =0
    
    @current_user.in_battle = true
    @current_user.save


    if params[:slota].present? || params[:slotb].present?


         spellboxes = []

         m = Spellbox.find_by :user_id => @current_user.id, :spell_id => params[:slota]  
         spellboxes << m if m.present?
         m = Spellbox.find_by :user_id => @current_user.id, :spell_id => params[:slotb]
         spellboxes << m if m.present?

         spellboxes.each do |box|
            if box.amount >= 1
                box.amount += -1
                box.save
                spell_stat = Spell.find box.spell_id
                atk += spell_stat.attack
                dmg += spell_stat.damage
                defence += spell_stat.defence
                spd += spell_stat.speed

                if box.amount <=0
                  box.destroy
                end
            end

         end
    end

    stats = []

    if atk != 0
     stats << atk << dmg << defence<<spd
    end


    
     monster = Monster.find params[:monster_id]

     blow_exchange(stats, monster)

     redirect_to :controller => 'monsters', :action => 'damage'
     
  end




  def result

      if @current_user.in_battle 
          if @current_user.health <= 0
            @result = "You Loose..try harder"
            user_looser
          else
            @result = "You WIN!"
            user_winner
          end
      end

  end



  def new
    @monster = Monster.new
  end

  def create
      @monster = Monster.new user_params
    if @monster.save
      redirect_to monsters_path
    end
  end

  def show
    @monster = Monster.find params[:id]
  end

  def edit
    @monster = Monster.find params[:id]
    render :new
  end

  def update
    monster = Monster.find params[:id]
    monster.update user_params
    redirect_to monster
  end

  def destroy
  monster = Monster.find params[:id]
  monster.destroy
  redirect_to monsters_path
  end


  private
  def user_params
    params.require(:monster).permit(:name, :attack, :damage, :defence, :rank, :xp, :gold, :level, :user_id, :rank, :affinity, :longitude, :latitude, :suburb, :state, :country, :alive, :tagged, :image, :speed, :health, :slota, :slotb, :monster_id, :max_health)
  end
end

app/helpers/monsters_helper.rb
module MonstersHelper

  def how_manyspells
    spell_cache = []

      @current_user.spells.all.each do |s|
        spell = s.name 
        spell = Spellbox.find_by :spell_id => s.id, :user_id => @current_user.id

          spell.amount.times do
            m = Spell.find s.id
            spell_cache << m
          end

      end
    spell_cache

  end


  def blow_exchange(stats, monster)
    atk = 0
   
    if stats.present?

        if stats.last >= monster.speed 
          @current_user.move_first = true
        else
          @current_user.move_first = false
        end

        atk = rand(20) + stats.first
        atk = atk >= 20 ? 20 : atk
        if atk >= monster.defence
             monster.injury = ( stats.second )
             monster.health += -monster.injury
        else
            monster.injury = 0
        end

        atk = rand(20) + monster.attack
        atk = atk >= 20 ? 20 : atk
        if atk >= stats.third
            @current_user.injury = monster.damage
            @current_user.health += -monster.damage
        else
          @current_user.injury = 0
        end


        if monster.health <= 0
          monster.alive = false
          monster.deaths +=1
        end

        if @current_user.health <= 0
          @current_user.deaths += 1
        end

    else #if you attack with no spells you die
      @current_user.health = 0
      @current_user.injury = @current_user.max_health
      monster.injury = 0
    end



    @current_user.save
    monster.save

  end   


  

end

app/views/monsters/attack.html.erb
<div class="ogreAttackWindow">


  <div class="ranking">
          <div class="ogreLevel"> 
            <div class="ogreHealth"><%= @monster.health %> </div><div class="lvl">Health</div> 
          </div>

          <div class="ogreLevel"> 
            <div class="lvlNum"><%= @monster.level %> </div><div class="lvl">Level</div> 
          </div>

            <div class="ogreLevel"> 
            <div class="lvlNum"><%= @monster.rank %> </div><div class="lvl">Rank</div> 
          </div>
  </div>

  <img class="ogrePic" src="<%= @monster.image %>"> 

  <div class="ogreStats">
    <p>Name: <span><%= @monster.name %></span></p>
    <p>Attack: <span><%= @monster.attack %></span></p>
    <p>Damage: <span><%= @monster.damage %></span></p>
    <p>Defence: <span><%= @monster.defence %></span></p>
    <p>Speed: <span><%= @monster.speed %></span></p>
    <p>Affinity: <span><%= @monster.affinity %></span></p>
    <p>Deaths: <span><%= @monster.deaths %></span></p>
  </div>

</div>

<form action="/damage" method="get">
  <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />

  <input type="hidden" name="monster_id" value="<%= @monster.id %>" >
 
  <button id="unleashFury">Unleash The Fury!</button>

</form>

app/views/monsters/damage.html.erb
<div id="blur">

<div id="monsterHealth">
<div class="monsterHealth">
  Health: <%=@monster.health %>
</div>
</div>


<div class="monsterBox">
<div class="monsterSize" style="background-image: url(<%= @monster.image %>)"></div>
</div>


<div id="yourHealth">
  <div class="yourHealth">Health: <%= @current_user.health%></div>
</div>

<div id="yourSpells">
  <div id="slota" data-spell= "n" data-stats= "0,0,0,0" data-eleid="n">add spell</div>
  <div id="slotb" data-spell= "n" data-stats= "0,0,0,0" data-eleid="n">add spell</div>
</div>

<div id="spellStat">
<div class="statAtk">Atk: </div>
<div class="statDmg">Dmg: </div>
<div class="statDef">Def: </div>
<div class="statSpd">Spd: </div>
</div>

<!-- <div id="attack">Cast Spells</div> -->

<form id="attackForm" action="/combat" method="post">
  <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
  <input id="slotaSend" type="hidden" name="slota" >
  <input id="slotbSend" type="hidden" name="slotb" >
  <input type="hidden" name="monster_id" value="<%= @monster.id %>" >
 
  <button id="attack">Cast Spells!</button>

</form>

</div>



<div id="inventory">
  <% @player_spells.each do |spell| %>

  <div class="inventory <%= spell.affinity %>" data-spell="<%= spell.affinity %>" data-spellid= <%= spell.id  %> 
  data-stats= <%= spell.attack.to_s + "," + spell.damage.to_s + "," + spell.defence.to_s + "," + spell.speed.to_s %> >
  <p>Atk: <%= spell.attack %> dmg: <%= spell.damage %> def: <%= spell.defence %> spd: <%= spell.speed %></p></div>
  <% end %>


</div>

<div id="projectile"></div>
</div>

app/views/monsters/index.haml
<div class="ogreAttackWindow">
<div class="ogreStats">

= link_to 'New monster', new_monster_path

%ol
  -@monsters.each do |monster|
    %li= link_to(monster.name, monster) 

</div>
</div>

app/views/monsters/new.haml
= form_for @monster do |f|
 %p
  = f.label :name
  = f.text_field :name, :autofocus => true
 %p
  = f.label :attack
  = f.number_field :attack
 %p
  = f.label :damage
  = f.number_field :damage
 %p
  = f.label :defence
  = f.number_field :defence
 %p
  = f.label :speed
  = f.number_field :speed
 %p
  = f.label :rank
  = f.text_field :rank
 %p
  = f.label :xp
  = f.number_field :xp
 %p
  = f.label :gold
  = f.number_field :gold
 %p
  = f.label :level
  = f.number_field :level
 %p
  = f.label :image
  = f.text_field :image
 %p
  = f.label :user_id
  = f.number_field :user_id

 %p
  = f.label :health
  = f.number_field :health

 %p
  = f.label :max_health
  = f.number_field :max_health

 %p
  = f.label :affinity
  = f.text_field :affinity

 %p
  = f.label :longitude
  = f.text_field :longitude

 %p
  = f.label :latitude
  = f.text_field :latitude
 %p
  = f.label :zipcode
  = f.text_field :zipcode
 %p
  = f.label :state
  = f.text_field :state
 %p
  = f.label :country
  = f.text_field :country
 %p
  = f.label :alive
  = f.check_box :alive
 %p
  = f.label :tagged
  = f.check_box :tagged



 %p
  = f.label :submit
  = f.submit

app/views/monsters/result.html.erb
<div id="result"> <%= @result %> </div>

app/views/monsters/show.html.erb
<div class="ogreAttackWindow">
<div class="ogreStats">
<h2> <%= @monster.name %></h2>

<p>Attack: <%= @monster.attack %></p>
<p>damage: <%= @monster.damage %></p>
<p>defence: <%= @monster.defence %></p>
<p>Level: <%= @monster.level %></p>
<p>Rank: <%= @monster.rank %></p>
<p>affinity: <%= @monster.affinity %></p>


<%= link_to 'Edit', edit_monster_path(@monster) %>
<%= link_to 'Delete', @monster, :method => 'delete', :data => {:confirm => "Are you sure"} %>

</div>

</div>