config/routes.rb
# == Route Map
#
#       Prefix Verb   URI Pattern                  Controller#Action
#  session_new GET    /session/new(.:format)       session#new
#         root GET    /                            pages#home
#   edit_users GET    /users/edit(.:format)        users#edit
#        users GET    /users(.:format)             users#index
#              POST   /users(.:format)             users#create
#     new_user GET    /users/new(.:format)         users#new
#         user PATCH  /users/:id(.:format)         users#update
#              PUT    /users/:id(.:format)         users#update
#              DELETE /users/:id(.:format)         users#destroy
#     monsters GET    /monsters(.:format)          monsters#index
#              POST   /monsters(.:format)          monsters#create
#  new_monster GET    /monsters/new(.:format)      monsters#new
# edit_monster GET    /monsters/:id/edit(.:format) monsters#edit
#      monster GET    /monsters/:id(.:format)      monsters#show
#              PATCH  /monsters/:id(.:format)      monsters#update
#              PUT    /monsters/:id(.:format)      monsters#update
#              DELETE /monsters/:id(.:format)      monsters#destroy
#       spells GET    /spells(.:format)            spells#index
#              POST   /spells(.:format)            spells#create
#    new_spell GET    /spells/new(.:format)        spells#new
#   edit_spell GET    /spells/:id/edit(.:format)   spells#edit
#        spell GET    /spells/:id(.:format)        spells#show
#              PATCH  /spells/:id(.:format)        spells#update
#              PUT    /spells/:id(.:format)        spells#update
#              DELETE /spells/:id(.:format)        spells#destroy
#        zones GET    /zones(.:format)             zones#index
#              POST   /zones(.:format)             zones#create
#     new_zone GET    /zones/new(.:format)         zones#new
#    edit_zone GET    /zones/:id/edit(.:format)    zones#edit
#         zone GET    /zones/:id(.:format)         zones#show
#              PATCH  /zones/:id(.:format)         zones#update
#              PUT    /zones/:id(.:format)         zones#update
#              DELETE /zones/:id(.:format)         zones#destroy
#        login GET    /login(.:format)             session#new
#              POST   /login(.:format)             session#create
#              DELETE /login(.:format)             session#destroy
#

Rails.application.routes.draw do

 get 'attack/:id' => 'monsters#attack', :as => 'monster_attack'

 get 'damage' => 'monsters#damage', :as => 'monster_damage'

 post 'combat' => 'monsters#combat', :as => 'monster_combat'

 get 'result' => 'monsters#result', :as => 'monster_result'



 get 'session/new'

 root :to => 'pages#home'

 get 'search' => 'pages#search'

 post 'search' => 'pages#anymon'



   resources :users, :except => [:edit] do   #rerouting for edit profile
    collection do
      get '/edit' => 'users#edit'
    end
  end

  resources :monsters, :spells, :zones

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'


end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string
#  admin           :boolean          default(FALSE)
#  password_digest :string
#  image           :text
#  deaths          :integer
#  highest_level   :integer
#  health          :integer
#  lng             :float
#  lat             :float
#  suburb          :string
#  country         :string
#  state           :string
#  xp              :integer
#  gold            :integer
#  slota           :integer
#  slotb           :integer
#  level           :integer
#  pkills          :integer
#  dkills          :integer
#  mkills          :integer
#  attackable      :boolean          default(FALSE)
#  in_battle       :boolean          default(FALSE)
#  attacker_id     :integer
#  created_at      :datetime
#  updated_at      :datetime



#

class User < ActiveRecord::Base
  
  has_secure_password


  validates :name, :presence => true
  validates :name, :uniqueness => true
  
  has_many :spellboxes
  has_many :spells, :through => :spellboxes
  has_many :monsters

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_if_admin, :only => [:index]
  include MonstersHelper

  def index
      @users = User.all
  end

  def show
    
    @user = User.find params[:id]
    @player_spells = how_manyspells
  end


  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to root_path
    else
      render :new   #returns back to sign up page with details
    end
  end

  def edit
    @user = @current_user
    render :new
  end

  def update
    user = @current_user    #only upate current user
    user.update user_params
    redirect_to root_path
  end


  private
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation, :image)
  end

  def check_if_admin
    redirect_to root_path unless @current_user.present? && @current_user.admin?
  end

end

app/helpers/users_helper.rb
module UsersHelper


def user_winner
  @current_user.max_health += 10
  @current_user.health = @current_user.max_health 
  @current_user.level += 1
  @current_user.highest_level = @current_user.level if @current_user.level > @current_user.highest_level
  @current_user.injury = 0
  @current_user.in_battle = false
  @current_user.mkills +=1
  mon = Monster.find_by :attacker_id => @current_user.id
  @current_user.gold += mon.gold
  @current_user.save

  reset_monster
end


def user_looser
  @current_user.deaths +=1
  @current_user.health = 120
  @current_user.max_health = 120
  @current_user.injury = 0
  @current_user.level = 1
  @current_user.in_battle = false
  @current_user.gold = 0
  @current_user.save

  reset_monster
end


def reset_monster
  mon = Monster.find_by :attacker_id => @current_user.id
  mon.health = mon.max_health
  mon.attacker_id = nil
  mon.injury = 0
  mon.alive = true
  mon.tagged = false

  mon.save
end




end

app/views/users/index.haml
#usersListed
  %ol
    -@users.each do |user|
      %li= user.name

app/views/users/new.haml
- if @user.errors.any?
  %ol#errorNess
    - @user.errors.full_messages.each do |msg|
      %li= msg



= form_for @user do |f|
  %p
    = f.label :name
    = f.text_field :name, :autofocus => true
  %p
    = f.label :password
    = f.password_field :password

  %p
    = f.label :password_confirmation
    = f.password_field :password_confirmation

  %p
    = f.label :image
    = f.text_field :image
  %p
    = f.label :submit
    = f.submit

app/views/users/show.html.erb
<div id="holdMe">
<h2> <%= @user.name %> 

<% if @user.id == @current_user.id %>
<%= link_to 'edit', edit_users_path %>
<% end %>

</h2>


<div class="monsterBox">
<div class="monsterSize" style="background-image: url(<%= @user.image %>)"></div>
</div> 


<div id="showPlayer">

  <div>
  <h3>Info</h3>
  <p>Level: <%= @user.level %></p>
  <p>Health:<%= @user.health%> / <%=@user.max_health %></p>
  <p>Gold: <%= @user.gold %></p>
  <p>Country: <%= @user.country %></p>
  <p>State: <%= @user.state %></p>
  
  </div>

  <div>
  <h3>Stats</h3>
  <p>Player kills: <%= @user.pkills %></p>
  <p>Monster kills: <%= @user.mkills %></p>
  <p>Dragons: <%= @user.dkills %></p>
  <p>Deaths: <%= @user.deaths %></p>
  <p>Highest level: <%= @user.highest_level %></p>
  </div>

</div>

<div id="userInventory">
  <% @player_spells.each do |spell| %>

  <div class="userInventory <%= spell.affinity %>" data-spell="<%= spell.affinity %>" data-spellid= <%= spell.id  %> 
  data-stats= <%= spell.attack.to_s + "," + spell.damage.to_s + "," + spell.defence.to_s + "," + spell.speed.to_s %> >
  <p>Atk: <%= spell.attack %> dmg: <%= spell.damage %> def: <%= spell.defence %> spd: <%= spell.speed %></p></div>
  <% end %>


</div>




</div>